### ISSUE TITLE
container crashes when I use my own ServerGameSettings.json and ServerHostSettings.json

### ISSUE THREAD

**Issue by mouarflenoob** [Mephi00/v-rising-wine-docker-image#22]
Hello, and thank you for creating this image. Thanks also for being responsible for me starting to learn docker :) \o/

Everything is in the title : when I start the container without specifying any settings, it starts well (it's even using my own save files from my solo game), but as soon as I put the json files in the settings folder, it cannot load anymore. More precisely, it crashes in the middle of loading, and stays locked until I manually stop the container.

I attached my settings files. I had to rename in .txt because github would not accept json, but they are correctly named on my server.
[log too long, I attached the file too.]
do you have any idea as to why it does this ?

Thanks.
[ServerGameSettings.txt](https://github.com/Mephi00/v-rising-wine-docker-image/files/9418078/ServerGameSettings.txt)
[ServerHostSettings.txt](https://github.com/Mephi00/v-rising-wine-docker-image/files/9418079/ServerHostSettings.txt)
[logsDockerVRising.log](https://github.com/Mephi00/v-rising-wine-docker-image/files/9418106/logsDockerVRising.log)

**Comment by SteveOverflow128** [comment]
I'm not sure this is your root cause, but your settings are invalid. Looking through the logs there is a stack trace that points to the bad setting:

> v-rising-GangFang  | OverflowException: Value was either too large or too small for an unsigned byte.
...
v-rising-GangFang  | Rethrow as JsonSerializationException: Error converting value 320 to type 'System.Byte'. Path 'CastleStatModifiers_Global.HeartLimits.Level4.FloorLimit', line 177, position 25.`

You have the Level 4 castle floor limit set to 320 but the largest value that can be held there is 255. Fixing this might let you start up properly.

**Comment by mouarflenoob** [comment]
Thank you for your help, I changed the value and the server started and it works perfectly.

Thanks a lot !
